### ISSUE TITLE
Initializing a new plugin throws SyntaxError: The requested module 'fs' does not provide an export named 'cpSync'

### ISSUE THREAD

**Issue by orr3** [tobua/create-react-native-plugin#1]
Both `npx create-react-native-plugin react-native-my-plugin` and `npm init -y react-native-plugin react-native-my-plugin` fails on Node v.14.
```
file:///root/.npm/_npx/61060/lib/node_modules/create-react-native-plugin/index.js:3
import { existsSync, unlinkSync, rmdirSync, lstatSync, mkdirSync, cpSync, renameSync } from 'fs'
                                                                  ^^^^^^
SyntaxError: The requested module 'fs' does not provide an export named 'cpSync'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)
```
Seems like `cpSync` was introduced in Node V.16 and support is still experimental. See https://nodejs.org/api/fs.html#fscpsyncsrc-dest-options.

```
node -v
v14.19.3
npm -v
6.14.17
```

I'll go ahead and upgrade my Node environment but I think it would benefit the community if this awesome plugin would use an api generally available for more node versions.

**Comment by tobua** [comment]
Thanks for giving the plugin a try! I've recently upgraded this plugin to `cpSync` from `fs-extra` which doesn't yet support ES Modules. Seems like `cpSync` is the way to go and I've generally started using it.

It's unfortunate that it requires node 16, but since it's already in LTS, I'll just add a note in the README and adapt engines in `package.json`. Hope that'll do.

**Comment by orr3** [comment]
Thanks for your comment. That'll do just fine. I overcame the problem by upgrading node :)
